import { average, roundNumber, uniqueStrings } from './helpers.js';
import { runAvailableHarnesses } from './ai.js';

const VISION_SCHEMA = {
  type: 'object',
  properties: {
    summary: { type: 'string' },
    findability: { type: 'number' },
    comprehension: { type: 'number' },
    trust: { type: 'number' },
    satisfaction: { type: 'number' },
    accessibility: { type: 'number' },
    visual_bug_risk: { type: 'number' },
    friction_points: { type: 'array', items: { type: 'string' } },
    notes: { type: 'array', items: { type: 'string' } },
  },
  required: [
    'summary',
    'findability',
    'comprehension',
    'trust',
    'satisfaction',
    'accessibility',
    'visual_bug_risk',
    'friction_points',
    'notes',
  ],
  additionalProperties: false,
};

function aggregateVisionResults(results) {
  const successful = results.filter((result) => result.output);

  if (!successful.length) {
    return null;
  }

  return {
    summary: uniqueStrings(successful.map((result) => result.output.summary)).join(' '),
    findability: roundNumber(average(successful.map((result) => result.output.findability))),
    comprehension: roundNumber(average(successful.map((result) => result.output.comprehension))),
    trust: roundNumber(average(successful.map((result) => result.output.trust))),
    satisfaction: roundNumber(average(successful.map((result) => result.output.satisfaction))),
    accessibility: roundNumber(average(successful.map((result) => result.output.accessibility))),
    visual_bug_risk: roundNumber(average(successful.map((result) => result.output.visual_bug_risk))),
    friction_points: uniqueStrings(successful.flatMap((result) => result.output.friction_points)).slice(0, 8),
    notes: uniqueStrings(successful.flatMap((result) => result.output.notes)).slice(0, 8),
    by_harness: successful.map((result) => ({
      harness: result.harness,
      ...result.output,
    })),
  };
}

function heuristicVisionAnalysis({ persona, scenario, pageState, screenshotPath }) {
  const denseCopy = pageState.visibleText.length > 600;
  const tooManyChoices = pageState.candidates.length > 8;
  const clearHeadline = Boolean(pageState.title && pageState.headings?.length);
  const lowPatience = persona.behavioral_traits?.patience === 'low';

  const findability = roundNumber(Math.max(3, 8 - (tooManyChoices ? 2.5 : 0) - (pageState.candidates.length <= 1 ? 1 : 0)));
  const comprehension = roundNumber(Math.max(3, 8 - (denseCopy ? 2.5 : 0) - (clearHeadline ? 0 : 1.5) - (lowPatience ? 0.8 : 0)));
  const trust = roundNumber(Math.max(4, 7 + (clearHeadline ? 0.5 : -0.8)));
  const satisfaction = roundNumber(average([findability, comprehension, trust]) - (lowPatience ? 0.6 : 0));
  const accessibility = roundNumber(Math.max(4, 7 - (tooManyChoices ? 1.5 : 0)));

  return {
    summary: `Fallback visual analysis for ${scenario.name}: the page presents ${pageState.candidates.length} visible action(s) and ${denseCopy ? 'dense' : 'moderate'} on-screen copy.`,
    findability,
    comprehension,
    trust,
    satisfaction,
    accessibility,
    visual_bug_risk: 2,
    friction_points: uniqueStrings([
      tooManyChoices ? 'Navigation exposes many competing choices at once.' : '',
      denseCopy ? 'The page relies on text density more than scannable structure.' : '',
      lowPatience ? 'Low-patience personas may lose momentum before acting.' : '',
    ]).slice(0, 4),
    notes: [
      `Screenshot captured at ${screenshotPath}.`,
      'This analysis was generated by the local fallback after the external harness did not return in time.',
    ],
    by_harness: [],
  };
}

export async function analyzeSnapshotWithHarnesses({
  root = process.cwd(),
  harnessConfig,
  screenshotPath,
  persona,
  scenario,
  pageState,
}) {
  const prompt = [
    'You are evaluating a browser screenshot and page summary for a simulated user test.',
    `Persona: ${persona.name} (${persona.archetype})`,
    `Behavioral traits: ${JSON.stringify(persona.behavioral_traits || {})}`,
    `Scenario: ${scenario.name}`,
    `Scenario description: ${scenario.description || ''}`,
    `Success criteria: ${(scenario.success_criteria || []).join(' | ')}`,
    `Current URL: ${pageState.url}`,
    `Page title: ${pageState.title}`,
    `Headings: ${pageState.headings.join(' | ')}`,
    `Visible actions: ${pageState.candidates.map((candidate) => `${candidate.id}:${candidate.text}`).join(' | ')}`,
    `Visible text excerpt: ${pageState.visibleText}`,
    'Return concise scores from 1-10 plus friction notes focused on what this persona would experience visually.',
  ].join('\n');

  let results = await runAvailableHarnesses({
    root,
    harnessConfig,
    prompt,
    schema: VISION_SCHEMA,
    imagePaths: screenshotPath ? [screenshotPath] : [],
  });
  let aggregate = aggregateVisionResults(results);

  if (!aggregate) {
    aggregate = heuristicVisionAnalysis({
      persona,
      scenario,
      pageState,
      screenshotPath,
    });
  }

  return {
    aggregate,
    raw: results,
  };
}
